name    = "thor"
version = "0.3.0"
out     = "build/"
entry   = "src/main.zp"
flags   = "-Lvendor/zap-toml/lib -lztoml"

[imports]
"@zap-sfml" = "./vendor/zap-sfml/src/lib"
"@toml" = "./vendor/zap-toml/src"



[dependencies]
"zap-sfml" = { url = "https://github.com/funcieqDEV/zap-sfml", version = "06588a7cf682abd30d30f2c893cac32386c9d250", commit = "06588a7cf682abd30d30f2c893cac32386c9d250" }
"zap-sfml" = { url = "https://github.com/funcieqDEV/zap-sfml", version = "06588a7cf682abd30d30f2c893cac32386c9d250", commit = "06588a7cf682abd30d30f2c893cac32386c9d250" }
